apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: drugdealer-worker
spec:
  selector:
    matchLabels:
      app: drugdealer-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: drugdealer-worker
    spec:
      containers:
      - name: drugdealer-worker
        image: mukundkalantri23/drugdealer-worker:latest
        env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: MINIO_HOST
              value: "minio:9000"
            - name: db_root_password
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: db_name
              value: drugdealer
            - name: table_name
              value: data
            - name: SENDGRID_API_KEY
              value: "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"
            - name: SENDGRID_VERIFIED_SENDER
              value: "mukundkalantri23@gmail.com"
        ports:
        - containerPort: 5002
